<a href="https://colab.research.google.com/github/Aman1477r/ML-journey/blob/main/Ml%20day%3D9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [114]:
import pandas as pd

In [115]:
s = pd.Series([10,20,30,40,50])

In [116]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [117]:
s.dtype

dtype('int64')

In [118]:
s.info()

<class 'pandas.core.series.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [119]:
s.describe()

count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64

In [120]:
s.name = 'name'

In [121]:
s

0    10
1    20
2    30
3    40
4    50
Name: name, dtype: int64

In [122]:
s.index[2]

2

In [123]:
s.iloc[2]

np.int64(30)

In [124]:
s.iloc[2:3]

2    30
Name: name, dtype: int64

In [125]:
s.iloc[1:4]

1    20
2    30
3    40
Name: name, dtype: int64

In [126]:
index = ['apple','banana','mango','pineapple','kewi']

In [127]:
s

0    10
1    20
2    30
3    40
4    50
Name: name, dtype: int64

In [128]:
index

['apple', 'banana', 'mango', 'pineapple', 'kewi']

In [129]:
s.index = index

In [130]:
s

apple        10
banana       20
mango        30
pineapple    40
kewi         50
Name: name, dtype: int64

In [131]:
s.name = 'calories'

In [132]:
s

apple        10
banana       20
mango        30
pineapple    40
kewi         50
Name: calories, dtype: int64

In [133]:
s['apple']

np.int64(10)

In [134]:
s.loc['apple']

np.int64(10)

In [135]:
s.iloc[2]

np.int64(30)

In [136]:
fruit_protein = {
    'apple':10,
    'banana':20,
    'mango':30,
    'pineapple':40,
    'kewi':50
}

In [137]:
s2 = pd.Series(fruit_protein,name= 'protein')

In [138]:
s2

apple        10
banana       20
mango        30
pineapple    40
kewi         50
Name: protein, dtype: int64

In [139]:
### COnditional selection

s2[s2>1]

apple        10
banana       20
mango        30
pineapple    40
kewi         50
Name: protein, dtype: int64

In [140]:
### Logical oprator

s2[(s2>10) & (s2<80)]

banana       20
mango        30
pineapple    40
kewi         50
Name: protein, dtype: int64

In [141]:
### modify seris

s2['apple'] = 90

In [142]:
s2

apple        90
banana       20
mango        30
pineapple    40
kewi         50
Name: protein, dtype: int64

In [143]:
import numpy as np

In [144]:
ser = pd.Series(['a',np.nan,1,np.nan,2])

In [145]:
s.isnull().sum()

np.int64(0)

In [146]:
s.notnull().sum()

np.int64(5)

In [147]:
data = {
    "Name":["Jai", "Princi", "Gaurav", "Anuj"],
    "Age":[27, 24, 22, 32],
    "Department": ["HR","IT","Financ","HR"],
    "Salary" : [80000,4000,5000,np.nan]
}

In [148]:
data

{'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
 'Age': [27, 24, 22, 32],
 'Department': ['HR', 'IT', 'Financ', 'HR'],
 'Salary': [80000, 4000, 5000, nan]}

In [149]:
df = pd.DataFrame(data)

In [150]:
df

     Name  Age Department   Salary
0     Jai   27         HR  80000.0
1  Princi   24         IT   4000.0
2  Gaurav   22     Financ   5000.0
3    Anuj   32         HR      NaN

In [151]:
df.head()

     Name  Age Department   Salary
0     Jai   27         HR  80000.0
1  Princi   24         IT   4000.0
2  Gaurav   22     Financ   5000.0
3    Anuj   32         HR      NaN

In [152]:
df[['Age','Salary']]

   Age   Salary
0   27  80000.0
1   24   4000.0
2   22   5000.0
3   32      NaN

In [153]:
df.drop("Age",axis=1,inplace=False)

     Name Department   Salary
0     Jai         HR  80000.0
1  Princi         IT   4000.0
2  Gaurav     Financ   5000.0
3    Anuj         HR      NaN

In [154]:
df

     Name  Age Department   Salary
0     Jai   27         HR  80000.0
1  Princi   24         IT   4000.0
2  Gaurav   22     Financ   5000.0
3    Anuj   32         HR      NaN

In [155]:
df.shape

(4, 4)

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      object
 1   Age         4 non-null      int64
 2   Department  4 non-null      object
 3   Salary      3 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes

In [157]:
df.describe()

             Age        Salary
count   4.000000      3.000000
mean   26.250000  29666.666667
std     4.349329  43592.812863
min    22.000000   4000.000000
25%    23.500000   4500.000000
50%    25.500000   5000.000000
75%    28.250000  42500.000000
max    32.000000  80000.000000

In [158]:
df['Salary'] =df['Salary'] + 5000

In [159]:
df['Salary']

0    85000.0
1     9000.0
2    10000.0
3        NaN
Name: Salary, dtype: float64

In [160]:
df

     Name  Age Department   Salary
0     Jai   27         HR  85000.0
1  Princi   24         IT   9000.0
2  Gaurav   22     Financ  10000.0
3    Anuj   32         HR      NaN

In [161]:
### Rename

df.rename(columns={"Department": "Dept"}, inplace=True)

In [162]:
df

     Name  Age    Dept   Salary
0     Jai   27      HR  85000.0
1  Princi   24      IT   9000.0
2  Gaurav   22  Financ  10000.0
3    Anuj   32      HR      NaN

In [163]:
df["Salary"].unique()

array([85000.,  9000., 10000.,    nan])

In [164]:
df["Dept"].value_counts()

Dept
HR        2
IT        1
Financ    1
Name: count, dtype: int64

In [165]:
df["promoted_salry"] = df["Salary"] * 10

In [166]:
df

     Name  Age    Dept   Salary  promoted_salry
0     Jai   27      HR  85000.0        850000.0
1  Princi   24      IT   9000.0         90000.0
2  Gaurav   22  Financ  10000.0        100000.0
3    Anuj   32      HR      NaN             NaN

In [167]:
df.isnull().sum()

Name              0
Age               0
Dept              0
Salary            1
promoted_salry    1
dtype: int64

In [168]:
df.dropna(how = "any")

     Name  Age    Dept   Salary  promoted_salry
0     Jai   27      HR  85000.0        850000.0
1  Princi   24      IT   9000.0         90000.0
2  Gaurav   22  Financ  10000.0        100000.0

In [169]:
df

     Name  Age    Dept   Salary  promoted_salry
0     Jai   27      HR  85000.0        850000.0
1  Princi   24      IT   9000.0         90000.0
2  Gaurav   22  Financ  10000.0        100000.0
3    Anuj   32      HR      NaN             NaN

In [170]:
df.dropna(how = "all")

     Name  Age    Dept   Salary  promoted_salry
0     Jai   27      HR  85000.0        850000.0
1  Princi   24      IT   9000.0         90000.0
2  Gaurav   22  Financ  10000.0        100000.0
3    Anuj   32      HR      NaN             NaN

In [171]:
df.fillna(0)

     Name  Age    Dept   Salary  promoted_salry
0     Jai   27      HR  85000.0        850000.0
1  Princi   24      IT   9000.0         90000.0
2  Gaurav   22  Financ  10000.0        100000.0
3    Anuj   32      HR      0.0             0.0

In [172]:
df['Age'].fillna(df['Age'].mean())

0    27
1    24
2    22
3    32
Name: Age, dtype: int64

In [173]:
df['Salary'].fillna(df['Salary'].median())

0    85000.0
1     9000.0
2    10000.0
3    10000.0
Name: Salary, dtype: float64

In [174]:
df['Salary'].fillna(method = 'ffill')

/tmp/ipykernel_1540/694346041.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Salary'].fillna(method = 'ffill')

0    85000.0
1     9000.0
2    10000.0
3    10000.0
Name: Salary, dtype: float64

In [175]:
df

     Name  Age    Dept   Salary  promoted_salry
0     Jai   27      HR  85000.0        850000.0
1  Princi   24      IT   9000.0         90000.0
2  Gaurav   22  Financ  10000.0        100000.0
3    Anuj   32      HR      NaN             NaN

In [176]:
df["Name"] = df["Name"].replace("Jai","Ashish")

In [177]:
df

     Name  Age    Dept   Salary  promoted_salry
0  Ashish   27      HR  85000.0        850000.0
1  Princi   24      IT   9000.0         90000.0
2  Gaurav   22  Financ  10000.0        100000.0
3    Anuj   32      HR      NaN             NaN

In [178]:
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

In [179]:
df_dup = df[df.duplicated(keep="last")]

In [180]:
df_dup

Empty DataFrame
Columns: [Name, Age, Dept, Salary, promoted_salry]
Index: []

In [181]:
df = df.drop_duplicates()

In [182]:
df

     Name  Age    Dept   Salary  promoted_salry
0  Ashish   27      HR  85000.0        850000.0
1  Princi   24      IT   9000.0         90000.0
2  Gaurav   22  Financ  10000.0        100000.0
3    Anuj   32      HR      NaN             NaN

In [183]:
### Invalid Value Using lamda

df["promoted_salry"] = df["promoted_salry"].apply(lambda x: x/10 if x > 650000 else x)

In [184]:
df

     Name  Age    Dept   Salary  promoted_salry
0  Ashish   27      HR  85000.0         85000.0
1  Princi   24      IT   9000.0         90000.0
2  Gaurav   22  Financ  10000.0        100000.0
3    Anuj   32      HR      NaN             NaN

In [185]:
def multiplying_age(x):
  return x*2
df["Age"] = df["Age"].apply(multiplying_age)

In [186]:
df

     Name  Age    Dept   Salary  promoted_salry
0  Ashish   54      HR  85000.0         85000.0
1  Princi   48      IT   9000.0         90000.0
2  Gaurav   44  Financ  10000.0        100000.0
3    Anuj   64      HR      NaN             NaN

In [187]:
df["Age"] = df["Age"].apply(lambda x: x/2)

In [188]:
df

     Name   Age    Dept   Salary  promoted_salry
0  Ashish  27.0      HR  85000.0         85000.0
1  Princi  24.0      IT   9000.0         90000.0
2  Gaurav  22.0  Financ  10000.0        100000.0
3    Anuj  32.0      HR      NaN             NaN

In [189]:
### joins and merges

df2 = pd.DataFrame({
    "Location" : ["pune","mumbai","hydrabad"],
    "Manager" : ["lona","seniii","Nina"]
})

In [190]:
pd.concat([df,df2])

     Name   Age    Dept   Salary  promoted_salry  Location Manager
0  Ashish  27.0      HR  85000.0         85000.0       NaN     NaN
1  Princi  24.0      IT   9000.0         90000.0       NaN     NaN
2  Gaurav  22.0  Financ  10000.0        100000.0       NaN     NaN
3    Anuj  32.0      HR      NaN             NaN       NaN     NaN
0     NaN   NaN     NaN      NaN             NaN      pune    lona
1     NaN   NaN     NaN      NaN             NaN    mumbai  seniii
2     NaN   NaN     NaN      NaN             NaN  hydrabad    Nina

In [191]:
pd.concat([df,df2],axis=1)

     Name   Age    Dept   Salary  promoted_salry  Location Manager
0  Ashish  27.0      HR  85000.0         85000.0      pune    lona
1  Princi  24.0      IT   9000.0         90000.0    mumbai  seniii
2  Gaurav  22.0  Financ  10000.0        100000.0  hydrabad    Nina
3    Anuj  32.0      HR      NaN             NaN       NaN     NaN

In [197]:
dfff = pd.read_csv('raw_dataset.csv')

In [198]:
dfff

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1.0,5953.0
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1.0,5953.0
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1.0,5956.0
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1.0,5955.0
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1.0,5955.0
...,...,...,...,...,...,...,...,...,...,...,...,...
218243,218243,Air_India,AI-889,Delhi,Morning,one,Afternoon,Kolkata,Business,27.58,37.0,42212.0
218244,218244,Air_India,AI-839,Delhi,Night,one,Morning,Kolkata,Business,10.67,37.0,43376.0
218245,218245,Air_India,AI-544,Delhi,Evening,one,Morning,Kolkata,Business,14.83,37.0,43376.0
218246,218246,Air_India,AI-542,Delhi,Morning,one,Morning,Kolkata,Business,22.33,37.0,43376.0
218247,218247,Air_India,AI-560,Delhi,Morni,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [199]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      float64
 2   Dept            4 non-null      object
 3   Salary          3 non-null      float64
 4   promoted_salry  3 non-null      float64
dtypes: float64(3), object(2)
memory usage: 292.0+ bytes