<a href="https://colab.research.google.com/github/Aman1477r/ML-journey/blob/main/ML_Day_%3D_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

1. ## One Hot Encoding


One-Hot Encoding converts each category into a separate binary column containing 0s and 1s.


Nominal data (categories with no order)
Features with a small number of unique values
Advantage

In [54]:
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']

})

In [ ]:
encoder = OneHotEncoder()

In [ ]:
encodee= encoder.fit_transform(df[['color']]).toarray()

In [ ]:
dff = pd.DataFrame(encodee,columns=encoder.get_feature_names_out())

In [ ]:
dff

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [ ]:
import seaborn as sns

In [12]:
df=sns.load_dataset('tips')

In [13]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [15]:
enddd = encoder.fit_transform(df[['day']]).toarray()

In [16]:
df2 = pd.DataFrame(enddd,columns=encoder.get_feature_names_out())

In [17]:
df2

     day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [18]:
encoder.get_feature_names_out()

array(['day_Fri', 'day_Sat', 'day_Sun', 'day_Thur'], dtype=object)

In [30]:
sex2 = encoder.fit_transform(df[['sex']]).toarray()

In [23]:
encoder.get_feature_names_out()

array(['sex_Female', 'sex_Male'], dtype=object)

In [29]:
df3= pd.DataFrame(sex2,columns=encoder.get_feature_names_out())

In [28]:
df3

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [34]:
bill = encoder.fit_transform(df[['time']]).toarray()

In [36]:
df4= pd.DataFrame(bill,columns=encoder.get_feature_names_out())

In [37]:
df4

     time_Dinner  time_Lunch
0            1.0         0.0
1            1.0         0.0
2            1.0         0.0
3            1.0         0.0
4            1.0         0.0
..           ...         ...
239          1.0         0.0
240          1.0         0.0
241          1.0         0.0
242          1.0         0.0
243          1.0         0.0

[244 rows x 2 columns]

2 ## Label encoding

> Label Encoding assigns a unique integer value to each category in a feature.

Example
Gender	Encoded
Male	  0
Female	1

In [38]:
from sklearn.preprocessing import LabelEncoder

In [45]:
labl_enco = LabelEncoder()

In [47]:
labl_enco.fit_transform(df['color'])

array([2, 0, 1, 1, 2, 0])

2 ### Ordinal encoding
Ordinal Encoding assigns numerical values to categories based on their natural order or ranking.

Example
Size
Small
Medium
Large

In [49]:
from sklearn.preprocessing import OrdinalEncoder

In [56]:
sdd = pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [57]:
sdd

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [58]:
ordinal_en = OrdinalEncoder()

In [59]:
ordinal_en.fit_transform(sdd)

array([[2.],
       [1.],
       [0.],
       [1.],
       [2.],
       [0.]])

In [67]:
ordinal_en.transform([['small']])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[2.]])

#### TARGEEEEET Encoding


Target Encoding replaces each category with the average value of the target variable for that category.

Example
City	Purchased
Mumbai	1
Mumbai	0
Delhi	1

In [68]:
import pandas as pd

In [71]:
gg = pd.DataFrame({
    'city': ['New York','Los Angeles','Chicago','New York','Chicago'],
    'price': [200,400,500,600,700]
})

In [72]:
gg

          city  price
0     New York    200
1  Los Angeles    400
2      Chicago    500
3     New York    600
4      Chicago    700

In [79]:
mean_price =  gg.groupby('city')['price'].mean()

In [80]:
gg['encoded_data'] = gg['city'].map(mean_price)

In [81]:
gg

          city  price  encoded_data
0     New York    200         400.0
1  Los Angeles    400         400.0
2      Chicago    500         600.0
3     New York    600         400.0
4      Chicago    700         600.0

In [84]:
gg[['price','encoded_data']]

   price  encoded_data
0    200         400.0
1    400         400.0
2    500         600.0
3    600         400.0
4    700         600.0